name: code

env:
  PROJECT_NAME: Kalk

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'site/**'
    - 'changelog.md'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build & test (Release)
      run: dotnet test src -c Release

    - name: Kalk.Releaser
      run: dotnet build src\Kalk.Releaser -c Release

    - name: Publish
      if: github.event_name == 'push'
      run: |
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+" ) {
              src\Kalk.Releaser\bin\Release\net5.0\krel.exe --nuget=${{secrets.NUGET_TOKEN}} --github=${{secrets.APP_GITHUB_TOKEN}}
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
